name: Calculate SHA-256 Checksum

on:
  push:
    branches: [ "main" ]
env:
  FORCE_COLOR: 1

jobs:
  calculate-checksum:
    name: Calculate SHA-256 Checksum
    runs-on: ubuntu-latest
    steps:

    - id: init
      run: |
        echo "hash=${{ github.sha }}" >> "$GITHUB_OUTPUT"
        echo "link=https://api.github.com/repos/${{ github.repository }}/tarball/${{ github.sha }}" >> "$GITHUB_OUTPUT"

    - id: download
      run: curl -L -o current_commit.tar.gz ${{ steps.init.outputs.link }}

    - id: checksum
      run: echo "sha256=$(sha256sum current_commit.tar.gz | awk '{print $1}')" >> "$GITHUB_OUTPUT"
    
    - name: Print summary
      run: |
        echo "### Checksum Calculated! :rocket:" >> $GITHUB_STEP_SUMMARY
        echo "Commit hash :link:" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo ${{ steps.init.outputs.hash }} >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "SHA-256 checksum :key:" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo ${{ steps.checksum.outputs.sha256 }} >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "[Download tarball](${{ steps.init.outputs.link }})" >> $GITHUB_STEP_SUMMARY